[[Antic]]
arch = "aarch64"
git-tree-sha1 = "7e837378804fe2a9b43bcff14330c8cafe85ba3a"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "ca25b448bd53e0077da9e17b66ed8c7dd3a09e77bc255214b32e561ab8fbdedb"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.aarch64-linux-gnu.tar.gz"
[[Antic]]
arch = "aarch64"
git-tree-sha1 = "7bc66bcbbfca57f540d3bd0bbb44ff71ee9f238c"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "79e1cc8235e9859eff8450fc74e9743a07a5aa5029807073ab9fdfdf733fef7f"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.aarch64-linux-musl.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "08b597fb9df07e0c79750eafaf31b25cd932a7b5"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "e42650cca91dcdf0a1b5273df314fe22f5c86215f8bbc029c211cf27ff8648a2"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.armv7l-linux-gnueabihf.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "b6f68a45cf6e056afe8cbe95769f457557511876"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "5090e1ce8630556a51568ab02f75d46c449b65b2e1e62ff55ee2fc4242fc74a2"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.armv7l-linux-musleabihf.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "91632514656c61735b1e7b01233db85003dcdd67"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "0a04ecfd5f008339113c248b8e61793e99092e0847663bac84b18a8c620bb3d4"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.i686-linux-gnu.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "2bb035bd8ec72bcbc7f31870145a6812be531906"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "50c41da5f42249773df30635661049603f46f46889a4f505d9bcbd35bb815326"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.i686-linux-musl.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "9c6a70204e55cb5e51a61d528fad1dea5dac9268"
os = "windows"

    [[Antic.download]]
    sha256 = "18cb0676d0dbd40b11e7e13ac5c22b75a00281641c8578c6c013663bd6ea0823"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.i686-w64-mingw32.tar.gz"
[[Antic]]
arch = "powerpc64le"
git-tree-sha1 = "b5b52d9233fe5cce359ba3e72b29f617e55c39e4"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "8b79f05b47c178708f88614d9d68d5a5368d2412b624a8ebb18ea31b35aa4071"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.powerpc64le-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "44a086e491c28f6199968df348e74972ebb4e56c"
os = "macos"

    [[Antic.download]]
    sha256 = "74d69faeae43dafcd4c4fc9898383dc4c64780bbb1810fae144e281349659830"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.x86_64-apple-darwin14.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "bca4c136600de62d44fa53af493afcbb1cf42eb9"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "5aad023466877aa331ff44c02ccc81d8a1d3388bd597126efed3b1e85450fdc6"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.x86_64-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "8c576a70819f54fee600ca13f9354f361fbfb3e1"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "ad2480bd9efbd7082223b925de3a4cad836ecfe19c1e27639c5cfd0be2f55b50"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.x86_64-linux-musl.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "fed011aacf34c3165a75b580a68a9c4adf23fb11"
os = "freebsd"

    [[Antic.download]]
    sha256 = "1642ab1bb43693d6c09e859ee0c6c25303f837d014d9b8196bf654be9aa1d65b"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "3692c3795bc0f59f8b3efdbd60d7ed92d0a86960"
os = "windows"

    [[Antic.download]]
    sha256 = "a4d0d7218bd15cfb93c7b8313c3906a86a59cf7cab2dff2ebd922b6558549ebc"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v2.1.0+0/Antic.v2.1.0.x86_64-w64-mingw32.tar.gz"
