[[Antic]]
arch = "aarch64"
git-tree-sha1 = "44e2996cee63c1ef3ad8f99c74a2c56fb84d258b"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "e7431f67579a968559e253bedea5addffc094ccde61908db20c8183466a9e6b6"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.aarch64-linux-gnu.tar.gz"
[[Antic]]
arch = "aarch64"
git-tree-sha1 = "6477dfaef1f86d8888ca87c2f420d34721b40f5d"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "3adb61c4e941bdac68f7b95e190970b0b789e4ac100630840535176b49d343b3"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.aarch64-linux-musl.tar.gz"
[[Antic]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1f1fb3e88e21c0922bc20da10ad5542489caa94f"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "d7d5788d5d035122b93be127487d7f499308431bf83db9fb3042eae4a1e5398e"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.armv7l-linux-gnueabihf.tar.gz"
[[Antic]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7987e0fe789c031d2ca4fd1cfa0687fc76c99811"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "852e9418f706f078001ae504f45b34c3ff351af5dc1662e4f20a770e3c2b5934"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.armv7l-linux-musleabihf.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "db8452f788841091f12701011bb78e607cf4128f"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "0f6eb1230051ff009be5f9f97348a7d66522918a966ca14f23b5275d1050d334"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.i686-linux-gnu.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "573ba7ae5ba4569899473bded80e2f1a04f72f0d"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "6a7f826851d861ce4cce945b71f58de08af30747b0deeacf35bfe91c47ad26ca"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.i686-linux-musl.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "59ab6e45f0d013346de70583d2dcd8491573e8cb"
os = "windows"

    [[Antic.download]]
    sha256 = "813d3776c62b6d3cc93a433cde2a1f1fbdd0a8222dda54cb1ed7278d160495b4"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.i686-w64-mingw32.tar.gz"
[[Antic]]
arch = "powerpc64le"
git-tree-sha1 = "e55e4cca03f80d705024976055f47778c8d2653e"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "024abc56473787ba01d718ebaf2cbe337f15dba83f754f8ba99da2ba6a6f7b92"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.powerpc64le-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "8f74f03c059824c84a5e45fb215b17042575fc18"
os = "macos"

    [[Antic.download]]
    sha256 = "a8f60ece9de12341fd316c42ea36a198a51fea14be939a5138f6dc082703a93a"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.x86_64-apple-darwin.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "51aa031422ee7d2a12a9d0fa03b4f1034da46eeb"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "ad4c7496e4009ae46257c6db7c9189561b2169094d2ec4bb32120eca36ca1fb4"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.x86_64-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "e45e408ab693aaba8f8aae122c17a319773e18b3"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "7c3f5402f33938c6574bb1e2bca43b389a7c2195b5d3bb5ebefe5e5e5267d699"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.x86_64-linux-musl.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "5d195d6f5f8271f3607c59504f8fb78543184754"
os = "freebsd"

    [[Antic.download]]
    sha256 = "0f11cde6f4279afa0647a7e963b24dc9fe8b3dc59f4de067cae1ca805eaaaa46"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.x86_64-unknown-freebsd.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "f4af7b9335a297f2c25f2387e6e3a97d1a3b2ebf"
os = "windows"

    [[Antic.download]]
    sha256 = "4b76e6f8694c199f0e825383e7f4a6aa47586e25b30203a8c6388fc441f26ce1"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.3+0/Antic.v0.2.3.x86_64-w64-mingw32.tar.gz"
