[[Antic]]
arch = "aarch64"
git-tree-sha1 = "a6c3839cdbbbeb9045075275565bd4e8beca7d4f"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "44dc61f306e9619028b1f08a316c9c6fd01fd5424b1ca6c376756b7bd4bbc870"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.aarch64-linux-gnu.tar.gz"
[[Antic]]
arch = "aarch64"
git-tree-sha1 = "29ae77be5553da3de4ee8bf13ab4f61333138961"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "3573010171ae00201fcd1b2979454da7d1624ebd286f65e8d488f9fe233e44eb"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.aarch64-linux-musl.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "b1c5831a5062e86d58b5e94858fc7d1306ffdecb"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "4cb1b1652877e31c70372ac04d0fab9d279ff6a646e5bafe2a8b8371b16ce871"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.armv7l-linux-gnueabihf.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "49cc67e0fb657517676f7bff37cebdcb64e8aaea"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "cff1577e7b01072ed9cfdb7c9cc5aecf06c0dd0de4647bf0971017f5f3aaca5c"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.armv7l-linux-musleabihf.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "cc31d84219affbebccd860b1cac2a5d5c2202784"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "e25e43ed4c6f270594164cb9d11e1b47b412c3526f6c26f6a01c0339d4256e58"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.i686-linux-gnu.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "29ec6658d361567e22981a0c35ea63ec38b5cee0"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "8df90842e173b09097e81cf8812c811c4fef314dcef0911427810abfc9152af3"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.i686-linux-musl.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "6d886aa33fe5c0524bfd73140ce43a600fb0a295"
os = "windows"

    [[Antic.download]]
    sha256 = "1059d29163922adf439611ab38fb0ba6b5c0c509b7cae7ae16a7bea9110889e4"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.i686-w64-mingw32.tar.gz"
[[Antic]]
arch = "powerpc64le"
git-tree-sha1 = "b67bcd39bb8337cfe8a09f440a622f7dc25649a9"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "f3934d459c5fbf71312f393eaeb1be8023300b38e8deb010f4c7c740b01ac0b0"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.powerpc64le-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "f39797aaf8c9e9107b243de2a5a420981d2d28ab"
os = "macos"

    [[Antic.download]]
    sha256 = "4c1cf4b75066b763d8e7201283ca89e30e5cb0e7242e117ee2603757af53c41e"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.x86_64-apple-darwin14.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "3484a5f49e5ec1effbb978fee58559386c94e4c6"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "51aaa2414f9749c02219f6daa116695f2683978b20973837edce7b085a1be3a5"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.x86_64-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "df8dc11b10c015b739e2fa5cf36e69bddc9006f0"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "b5a23de22a503532fc7a803ddbab8bfc59149b08fd77525fcf7987aeb45a85a9"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.x86_64-linux-musl.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "c91d0cfc20eee55cbee6989d2684dc2d392671e4"
os = "freebsd"

    [[Antic.download]]
    sha256 = "f1bff01277f9a525c39f5e67527203ecceeef5fda0d1c0bf8865c5876185b659"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "ec55deb1f58c1c1d21019afa26e2446211cdbeeb"
os = "windows"

    [[Antic.download]]
    sha256 = "7ae8476dff81b3742c63fe40e33679b90c5696af1c4735cea65cca4e430559c0"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+0/Antic.v0.2.1.x86_64-w64-mingw32.tar.gz"
