[[Antic]]
arch = "aarch64"
git-tree-sha1 = "44d39cfdf1fd8971ab27fa8ec343a3d5b461ae5f"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "5ba11ea40de9a08426b61584efcbbb87235c012d7effc0fdcf76bdcf2e644bab"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.aarch64-linux-gnu.tar.gz"
[[Antic]]
arch = "aarch64"
git-tree-sha1 = "1ba46ddce9389c1841e8b7cf042fa889f7c2be94"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "e0eae1417646ad612c4e697e6073c15771a5eaf0b64e261d1c4bcfa7ae486e4c"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.aarch64-linux-musl.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "56cb982851b2e80063e064cf510c60bccfdad403"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "b4c5379ebc5f877d208e178b71c671e1b577e35cee33f3518f8ba75509a0c490"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "d2a6ae7d85ab4cd72795347a321f455723e8da7d"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "c8ed191eba52415e824c98f47b6dec504db4fd246e562ee0495cae37638e9e01"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.armv7l-linux-musleabihf.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "d63d9f9e2982bde4546b1e1f2464be79e01e1467"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "9b517ce391d50dc717add7c367956614e3bc9bacdc1becc904afe96999f41f98"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.i686-linux-gnu.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "1d7da4a0d34ee5614dec050c809926fe58606957"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "c802fab9c67c2aac6ca79b47c2cafb466a30edfd8c36e8e229866f52a72ae7c1"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.i686-linux-musl.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "6c5e225864122974f290cdbea82b6b564b24706b"
os = "windows"

    [[Antic.download]]
    sha256 = "7f7952a8176e48b909b2bb3c89c747b10b7904ab413a2bad3a3c3886d38d1e9e"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.i686-w64-mingw32.tar.gz"
[[Antic]]
arch = "powerpc64le"
git-tree-sha1 = "d1c771aef60119fbda2eec832287189c1c5439bd"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "f0c440eb4a87b77a82a2f9db18886ca897fa0fe4d5cde64dbb599cb9cca7b5ce"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.powerpc64le-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "6745a36503fad6b19ee98fb6395e926767a212ef"
os = "macos"

    [[Antic.download]]
    sha256 = "e24baebb67b702e42720809d08e416975c3aed6826e445d243cb9c8f98e19ebe"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.x86_64-apple-darwin14.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "a70edf0344b0c824bcf2509a7da71d0800a4d86b"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "f783c2dc021f1d21b178f2ea04f176df2d3124c46a1628629bb0159d1f10de20"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.x86_64-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "5ebef1bc0fea99ef8630541a8089b5251e857cb5"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "61bc9cf797800b0086efc34011e21deba548e3d03f642cdbae9d43d320c253f0"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.x86_64-linux-musl.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "4937fef5528d60c2a3b4b063597df5ea9b4e883a"
os = "freebsd"

    [[Antic.download]]
    sha256 = "e10e0b1cdc98993003fc6ee505c8f06e9197a8702410fc927d5a0145e6053252"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "41a3cb60b23bea933d703d76001dc75d26dcdbcd"
os = "windows"

    [[Antic.download]]
    sha256 = "8e0fce48ff6e3b221c5d9cf6b1b5aadc7a126346be253f81138c2713a0ea28bf"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+2/Antic.v0.1.0.x86_64-w64-mingw32.tar.gz"
