[[Antic]]
arch = "aarch64"
git-tree-sha1 = "b6d74ece15e02b6af182e17157da17a8370928a9"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "68a4cda8e0fb0ca18c9a4227190f4abbac47756b90e92eb3259392e2a938038e"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.aarch64-linux-gnu.tar.gz"
[[Antic]]
arch = "aarch64"
git-tree-sha1 = "432398db701f3bc0bbef6a31fe8c809af0698ef6"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "c17fc03ae5eac617ae10a248a6c6aab7ff811ef36ae87ae2991e0eac57d31440"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.aarch64-linux-musl.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "d466bd35b09049df85acf54436ddd13d8ef3d284"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "bad694d204cdbecf9bbead54e2e0a10823e78b049d184b2484e405d99c09b7cf"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.armv7l-linux-gnueabihf.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "ff0ab421915426f24c652046cab4ac2d37609a9c"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "da6c6192b0c34f49f98d9a09d95787e2e2e0c0106707036d352431ebbbccd0db"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.armv7l-linux-musleabihf.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "3c5cf47c641409bcdaed057abb80736d90d28628"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "7f7fa34d0949f52a910b6e746a58a17cbc16d59bf2caad84370ca642e0c2f8e9"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.i686-linux-gnu.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "03a12d1fc46300a49d278adb5e3c91747e31c66e"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "b7b18a1d71d99070d6b6dcf4a8a7328a0db8ceeb3124eccd578b12fe0029b2b6"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.i686-linux-musl.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "97863bc7f5b021f7c3f8be106088dc459923f3c6"
os = "windows"

    [[Antic.download]]
    sha256 = "12e88db3b664043108f52fb7db486130489118bc8b52b8f0a98e08c2490dd248"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.i686-w64-mingw32.tar.gz"
[[Antic]]
arch = "powerpc64le"
git-tree-sha1 = "c003827d36d5146e0f63b6fe6f8126bbcfa7ba41"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "3aac78712370555efadf34f020b7de12ce68e254ba2b0b3fa51d6505ad4b8bd1"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.powerpc64le-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "733aca4f6e99b82917f6a261222bd217ca663beb"
os = "macos"

    [[Antic.download]]
    sha256 = "43941bc44590ff84596e8c4c29765505be52429e5138ff5cbed38a7f1096f24f"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.x86_64-apple-darwin14.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "fc1ba36a0f8320f4f3a85010799993a2989c98d6"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "3f8b8942e632830baf36609749d2920b465b2952e39f076bd1dadf6f6f8de7d2"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.x86_64-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "a99d1abb8d7d1d9aed3586eef6b1d7fe06aea326"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "7e1687fda66c8209b1f3386de45d9e7a6d251b4c0bd66743ef7c4dce5d333634"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.x86_64-linux-musl.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "a88194480fea655615e13d53605fa498893460d4"
os = "freebsd"

    [[Antic.download]]
    sha256 = "a93ed216b4eee736c8441993d8afe693a20cd13abb0c04b0fa3cb2759f46d7c5"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "8885c7d8083ddd49be2118bb61932f7472e8b566"
os = "windows"

    [[Antic.download]]
    sha256 = "6ff7a05b712cf7fc682db8d3b8f9b0898f8eb91cbbd89ca4c4ee27174587a681"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+2/Antic.v0.2.1.x86_64-w64-mingw32.tar.gz"
