[[Antic]]
arch = "aarch64"
git-tree-sha1 = "4f69b3ce5fb2dbbef4f991de471f3104716e51de"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "26820f90f0975f608caece27b421a4b71e5b1b2be49905ac89b96abae949ca83"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.aarch64-linux-gnu.tar.gz"
[[Antic]]
arch = "aarch64"
git-tree-sha1 = "260fc3d0a546e1fdc0dd639f62ca28db6eb7577b"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "76f80631815f7873dd40c9c836731d78548fc13d62632c1f47c444e1b16c3678"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.aarch64-linux-musl.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "918370560340ea103760c51a50ecae43fea8800f"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "342708aade30213ebd6fdc70ecf5a62ab19e5d846d5af8003fcbc7f7cf62d215"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "b27bf10b6f34a8f8c2bce2b48698bb3374f902b0"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "fc9737ce30f774e54eab9130aa173f706b88b289d7e6f188e2f68dc9546e71f3"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.armv7l-linux-musleabihf.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "1e9c5a89d03658febf6730cd62ac5bbe03dad44d"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "a01ea545a80a8d291ac8271e494fd5b6b4f5e98782018ad8eafcc3328a2dd82c"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.i686-linux-gnu.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "d8ce940677cf795729e724e1a6845ad8648c87ae"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "5ae5a04317094810a00e48908ca4ec19d3ec9d694b899de817a7f56c69bec619"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.i686-linux-musl.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "51e2155b111124b5ba0c6de03b2306a3aece44c2"
os = "windows"

    [[Antic.download]]
    sha256 = "4e330d2ebbb1759cfb297cbb83b52046309a21fa41e041d4d4c7243a015770a7"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.i686-w64-mingw32.tar.gz"
[[Antic]]
arch = "powerpc64le"
git-tree-sha1 = "d17d0bcce0c183b15fc3ae5241f80f085e3e8f75"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "a2306cc34b092ff63b12361088f5fd7d88105e1c1f58a0be1b4319898a90f24a"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.powerpc64le-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "2474a63b4624cb7a8cfe2a471267367e0742d80d"
os = "macos"

    [[Antic.download]]
    sha256 = "892f41a1184aa691e783ba864dc699104621a607f83dfaf6674248e914b3d2c4"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.x86_64-apple-darwin14.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "ad7c5938beed2ddb29ecb89d017ed5b822f4bc20"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "e2926aef3f1bb132d2fa276741ed4b11b7a3c4c02e854cb7825780ae74aaafc2"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.x86_64-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "17df1c905931f0bb38ada70bdab00b4a27e4d9fb"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "881249c99a30b3a0437427936b8f3987e568121c38a1df072da5d78df9a81fe7"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.x86_64-linux-musl.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "908cd0c8a260674548c00a0432c108246b513eb3"
os = "freebsd"

    [[Antic.download]]
    sha256 = "894a1edce0cc1010aef9ee8e76218370d031a02e53fb026bafbe89fb74ecbd93"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "1c5c2792638d1c92220e0c1d6357f217f18efd51"
os = "windows"

    [[Antic.download]]
    sha256 = "1c45fcc3ad0b4be155a6712f11e17e951572f88d13b380c8500d228123af710d"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.1.0+0/Antic.v0.1.0.x86_64-w64-mingw32.tar.gz"
