[[Antic]]
arch = "aarch64"
git-tree-sha1 = "f98299191a9bc4e3df1721dfe39bbb0adb463be0"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "e9ed8105e2e9350758b18f0508402bf5e4569d34fdfc7d153a9e7b907d4f1481"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.aarch64-linux-gnu.tar.gz"
[[Antic]]
arch = "aarch64"
git-tree-sha1 = "300860cd044f0f42d69ebdb3cfcf49a3f57feb38"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "deabce7f50a4afaba930e4cf1ed8f4d863b0e93210b330ab1d56e9259b1122a4"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.aarch64-linux-musl.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "607ccc85a75ab3ac2d92e49c4b820f7e4511c41b"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "be54ed0f6824a4903cfbc2ac91c3984086bd08f71f9fa011836b3ca4b6c81dbc"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.armv7l-linux-gnueabihf.tar.gz"
[[Antic]]
arch = "armv7l"
git-tree-sha1 = "85f9b6406f2fec3eb4f5b4d536001c6ac495d55c"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "1a80ef15c006629bcdc66ecf0a1f51f246df3acef5766ec0ced33b4542929c86"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.armv7l-linux-musleabihf.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "c80cefd97e8ca5911f7f65e548cfb414edcf27d4"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "69b32d8551feb93497ad770e018b860a48ede85d51bb8d50d710936a9482013d"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.i686-linux-gnu.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "16188bddc56c5f02a32053f4cc7a75e70d225ab1"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "026f1e866bbeef7512775d8e695b67cc55b41cdc733ab2b5a623031c482296ea"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.i686-linux-musl.tar.gz"
[[Antic]]
arch = "i686"
git-tree-sha1 = "c433b65df6f81e5d72897df96561f6928813ba3b"
os = "windows"

    [[Antic.download]]
    sha256 = "6d181628fed61a5282a861272c7207db262f5eb75bda43be37e62c81daccffd6"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.i686-w64-mingw32.tar.gz"
[[Antic]]
arch = "powerpc64le"
git-tree-sha1 = "b41c60b53ff0c150f78db1c18e2dcdedbc0d40f4"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "e17b00f2f29f043e60d701472c577eee7e4632418858a2a14602a54338919b4b"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.powerpc64le-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "c3b933b1ce2939d8d46be273e75fce0ea0099141"
os = "macos"

    [[Antic.download]]
    sha256 = "9ef965c0031acdd36162dd1f6b2b2ddb4471c9bfda1d066e3504ef8d0a989026"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.x86_64-apple-darwin14.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "5b605392dfaa2d81ae1399b6c0c160296667015e"
libc = "glibc"
os = "linux"

    [[Antic.download]]
    sha256 = "3fcb28745af5d9a731ccc7e7ac0b92ad25982169431dcee8591a8fe9071208d7"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.x86_64-linux-gnu.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "75b27331643fb6ed511490d06d8021aedfa547ab"
libc = "musl"
os = "linux"

    [[Antic.download]]
    sha256 = "e0574964c188fdc832cd690d7ed921e443acc81dfa79878ae21fa05be2c3a967"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.x86_64-linux-musl.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "e62f60d7afd32af728a73ef1ced035af724c5dce"
os = "freebsd"

    [[Antic.download]]
    sha256 = "b5febe8ab7aefef722529e70f6866fa7661c9b9f466cb48beeba4f179d938b15"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Antic]]
arch = "x86_64"
git-tree-sha1 = "48094186e7ca2828fadcad960bbf085835f019d3"
os = "windows"

    [[Antic.download]]
    sha256 = "dd1d97e9fe7a0d5bed7bb2ea3dee9c7b8af333d1d8539d8d734867936cd661f7"
    url = "https://github.com/JuliaBinaryWrappers/Antic_jll.jl/releases/download/Antic-v0.2.1+1/Antic.v0.2.1.x86_64-w64-mingw32.tar.gz"
