# Autogenerated wrapper script for Antic_jll for x86_64-apple-darwin
export libantic

using FLINT_jll
using GMP_jll
using MPFR_jll
JLLWrappers.@generate_wrapper_header("Antic")
JLLWrappers.@declare_library_product(libantic, "@rpath/libantic-0.2.4.dylib")
function __init__()
    JLLWrappers.@generate_init_header(FLINT_jll, GMP_jll, MPFR_jll)
    JLLWrappers.@init_library_product(
        libantic,
        "lib/libantic.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
